In [3]:
import torch
import torch.nn as nn

# 定义 MLP 模型
class MLP(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(MLP, self).__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, output_dim)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# 定义卷积网络模型
class ConvNet(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(ConvNet, self).__init__()
        self.conv1d = nn.Conv1d(input_dim, output_dim, kernel_size=1)

    def forward(self, x):
        x = self.conv1d(x)
        return x

# 输入数据维度
input_dim = 1024
# 输出数据维度
output_dim = 68

# 创建卷积网络模型
conv_net = ConvNet(input_dim, output_dim)

# 创建输入张量
input_tensor1 = torch.randn(7, 1024).unsqueeze(2)  # 添加一维作为通道维度
input_tensor2 = torch.randn(8, 1024).unsqueeze(2)

# 前向传播计算
output_tensor1 = conv_net(input_tensor1)
output_tensor2 = conv_net(input_tensor2)

# 调整输出张量的维度
output_tensor1 = output_tensor1.squeeze(2)
output_tensor2 = output_tensor2.squeeze(2)

# 打印输出张量的维度
print(output_tensor1.size())  # 输出: torch.Size([7, 68])
print(output_tensor2.size())  # 输出: torch.Size([8, 68])

/home/cnj/anaconda3/envs/amp_test/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


torch.Size([7, 68])
torch.Size([8, 68])


In [4]:
a = 'CYCQDPYVKEAENLKKYFNAGHSDVADNGTLFLGILKNWKEESDRKIMQSQIVSFYFKLFKNFKDDQSIQKSVETIKEDMNVKFFNSNEEVE'
len(a)

92

In [5]:
onpy_name = 'abc'

print(onpy_name + '.npy')

abc.npy


In [6]:
import numpy as np

b = np.load('/home/cnj/cs/test_methods/XU_pretrain_train_positive.npy', allow_pickle=True)

for i in b:
    print(i.shape)



FileNotFoundError: [Errno 2] No such file or directory: '/home/cnj/cs/test_methods/XU_pretrain_train_positive.npy'

In [ ]:
len(b)

4426

In [ ]:
from bio_embeddings.embed import SeqVecEmbedder

/home/cnj/anaconda3/envs/amp_test/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
import os 


def seq2vec_encoding(seqs, model_path):
    
    # * function to encode each residue in a single sequence into 1024 features
    # @param seq_ids: seqs array generated by `load_seqs`
    # @param model_path: folder contains the pretraining model weight of `SeqVecEmbedder`: 1. 'weights.hdf5'; 2. 'options.json'
    # @output: seqs to vec encoding list of the fasta sequences
    
    print('running seq2vec encoding ...')
    weights = os.path.join(model_path, 'weights.hdf5')
    options = os.path.join(model_path, 'options.json')
    
    seqs_vec_encoding = []

    seq_embedder = SeqVecEmbedder(weights_file=str(weights), options_file=str(options), cuda_device=0)
    
    for seq in seqs:
        seq2vec_embedding = seq_embedder.embed(seq)
        # residue_embedding = torch.tensor(seq2vec_embedding).sum(dim=0)
        residue_embedding = np.sum(seq2vec_embedding, axis=0) 
        seqs_vec_encoding.append(residue_embedding)
        # print(residue_embedding.shape)
        
    return seqs_vec_encoding


model_path = '/home/cnj/cs/peptide/myproject/seq2vec_pretrain_model'

/home/cnj/anaconda3/envs/trans/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


ImportError: cannot import name 'SeqVecEmbedder' from 'bio_embeddings.embed' (/home/cnj/anaconda3/envs/trans/lib/python3.8/site-packages/bio_embeddings/embed/__init__.py)

In [ ]:
from tqdm import tqdm

a = [[1,2], [3,4],[5,6]]

for i in tqdm(a):
    print(i)

100%|██████████| 3/3 [00:00<00:00, 43389.35it/s]

[1, 2]
[3, 4]
[5, 6]


In [ ]:
original_list = ['>LAMP_L12A09502', '>LAMP_L12A07556', '>LAMP|L11A000473', '>AMPfun_434']

modified_list = [element.replace('>', '').replace('|', '_') for element in original_list]

print(modified_list)

['LAMP_L12A09502', 'LAMP_L12A07556', 'LAMP_L11A000473', 'AMPfun_434']


In [ ]:
import numpy as np

# 假设feature是一个名为feature的NumPy数组
feature = np.array([0, 1, 2, 3, 4])

# 假设modified_list是你之前修改过的列表
modified_list = ['LAMP_L12A09502', 'LAMP_L12A07556', 'LAMP_L11A000473', 'AMPfun_434']

for file_name in modified_list:
    # 从feature数组中提取对应的元素
    element = feature[modified_list.index(file_name)]
    
    print(modified_list.index(file_name))
    # 将元素保存为.npy文件
    # np.save(file_name + '.npy', element)

0
1
2
3


In [ ]:
npz_folder = '/media/cnj/T9/data/test_data/positive/npz'
fasta_file = '/home/cnj/cs/test_methods/demo.fasta'

'/'.join(npz_folder.split('/')[:-1]) + '/hhm/'

'/media/cnj/T9/data/test_data/positive/hhm/'

In [ ]:
import torch.nn as nn
import torch

conv1 = nn.Conv1d(in_channels=256, out_channels=100, kernel_size=2)
input = torch.randn(32,35,256)
# batch_size x text_len x embedding_size -> batch_size x embedding_size x text_len
input = input.permute(0,2,1)
out = conv1(input)
print(out.size())

torch.Size([32, 100, 34])


In [ ]:
a = torch.randn(3,4,5)
a

tensor([[[-2.3557, -0.2822,  1.0779, -0.2345, -0.0851],
         [-0.9396, -1.0170, -0.8787,  0.0052, -0.2358],
         [ 0.4351,  1.6668, -1.8665,  0.3388, -0.5330],
         [ 0.0791, -0.8132,  0.1329,  0.8657,  1.6432]],

        [[-2.0244, -0.1173, -0.5782,  1.6109, -0.5153],
         [ 0.2387, -0.4315,  0.6108,  1.8983, -0.3509],
         [-0.2966, -0.7078,  0.0775, -0.3674, -1.0422],
         [-1.0057, -0.5215,  1.1750,  0.1869, -0.5250]],

        [[-0.4781, -0.0099,  0.0631,  2.6440,  1.6254],
         [ 0.2947,  1.2212, -0.5676,  0.3277, -0.5884],
         [-0.2158,  0.0890,  1.1776, -0.7869, -0.0622],
         [ 0.9943,  0.1731,  0.2692, -1.1863, -2.1312]]])

In [ ]:
a[0]

tensor([[-2.3557, -0.2822,  1.0779, -0.2345, -0.0851],
        [-0.9396, -1.0170, -0.8787,  0.0052, -0.2358],
        [ 0.4351,  1.6668, -1.8665,  0.3388, -0.5330],
        [ 0.0791, -0.8132,  0.1329,  0.8657,  1.6432]])

In [ ]:
a[0][0]

tensor([-2.3557, -0.2822,  1.0779, -0.2345, -0.0851])

In [ ]:
import random
# 设置循环次数
num_iterations = 5
list=[]
# 循环获取随机数
i = 0
while i < num_iterations:
    random_number = random.randint(5, 9)
    vec = torch.randn(random_number, 4)
    print(vec.shape)
    list.append(vec)
    i += 1
    
print(list[0])
print(list[1])
print(list[2])

torch.Size([8, 4])
torch.Size([5, 4])
torch.Size([6, 4])
torch.Size([7, 4])
torch.Size([6, 4])
tensor([[-0.7452,  1.2451,  1.3743,  0.6077],
        [ 0.0351,  0.2238, -0.2748,  1.2828],
        [-0.9276,  1.7167,  2.2772,  0.0730],
        [ 0.3406, -1.2217, -1.0129, -1.4818],
        [ 1.1417,  0.7242,  0.4656,  1.5999],
        [-0.1191, -0.8389,  0.5087,  1.0264],
        [-0.8180,  1.5677, -0.3932, -0.1825],
        [-1.0650,  1.9521, -0.7859, -1.4365]])
tensor([[-0.9088, -0.0756, -0.7647,  1.2211],
        [ 0.2193, -1.4624,  0.8282,  0.1934],
        [ 0.9841, -2.0314,  2.3655, -1.5870],
        [ 1.4287,  0.4612, -1.2353, -0.9411],
        [-1.7295,  0.7865,  1.6204,  1.2212]])


In [ ]:
kernel_size = 5
padding = kernel_size // 2
print(padding)

conv1 = nn.Conv1d(in_channels=16, out_channels=8, kernel_size=kernel_size, stride=1, padding=padding)
conv2 = nn.Conv1d(in_channels=8, out_channels=4, kernel_size=kernel_size, stride=1, padding=padding)

input = torch.randn(24, 5, 16)  # [batch_size, max_len, embedding_dim]
input = input.permute(0, 2, 1)    # 交换维度：[batch_size, embedding_dim, max_len]
out = conv1(input)                # [batch_size, out_channels, n+2p-f/s+1]
print(out.shape)      			  # torch.Size([32, 100, 33])

out2 = conv2(out)
print(out2.shape)



2
torch.Size([24, 8, 5])
torch.Size([24, 4, 5])


In [ ]:
import torch
import torch.nn as nn

# 定义MLP模型
class MLP(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(MLP, self).__init__()
        self.fc1 = nn.Linear(input_dim, 512)
        self.fc2 = nn.Linear(512, 128)
        self.fc3 = nn.Linear(128, 68)

    def forward(self, x):
        x = torch.flatten(x, start_dim=1)
        x = self.fc1(x)
        x = torch.relu(x)
        x = self.fc2(x)
        x = torch.relu(x)
        x = self.fc3(x)
        return x

# 创建MLP模型实例
input_dim = 100 * 2048
hidden_dim = 68
output_dim = 100 * 68
model = MLP(input_dim, hidden_dim, output_dim)

# 统计模型参数数量
total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print("Total parameters: {}".format(total_params))

    
    

Total parameters: 104932548


In [80]:
import torch
import torch.nn as nn

# 输入数据
input_data = torch.tensor([
    [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]],
    [[16, 17, 18, 19, 20], [21, 22, 23, 24, 25], [26, 27, 28, 29, 30]]], dtype=torch.float32)

# 创建卷积层
conv = nn.Conv1d(3, 2, kernel_size=(1,))
# conv = nn.Conv1d(3, 2, kernel_size=3, padding=1)
# 执行卷积操作
output_data = conv(input_data)

print("输入数据:")
print(input_data)
print("输出数据:")
print(output_data)

输入数据:
tensor([[[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.],
         [11., 12., 13., 14., 15.]],

        [[16., 17., 18., 19., 20.],
         [21., 22., 23., 24., 25.],
         [26., 27., 28., 29., 30.]]])
输出数据:
tensor([[[ -4.8972,  -5.8990,  -6.9007,  -7.9025,  -8.9043],
         [  2.0870,   1.6679,   1.2488,   0.8298,   0.4107]],

        [[-19.9240, -20.9258, -21.9276, -22.9294, -23.9312],
         [ -4.1992,  -4.6183,  -5.0374,  -5.4565,  -5.8756]]],
       grad_fn=<SqueezeBackward1>)


In [16]:
import torch
import torch.nn as nn

# 定义MLP模型
class CNNblock(nn.Module):
    def __init__(self):
        super(CNNblock, self).__init__()
        self.conv1 = nn.Sequential(nn.Conv1d(in_channels=2048, out_channels=512, kernel_size=3, stride=1, padding=1),
                                   nn.BatchNorm1d(num_features=512),
                                   nn.ReLU(),
                                   ) 
        
        self.conv2 = nn.Sequential(nn.Conv1d(in_channels=512, out_channels=128, kernel_size=3, stride=1, padding=1),
                                   nn.BatchNorm1d(num_features=128),
                                   nn.ReLU(),
                                   )

    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        # x = self.conv3(x)
        return x


# 创建MLP模型实例
input_dim = 100 * 1024
hidden_dim = 68
output_dim = 100 * 68
kernel_size=3
model = CNNblock()

# 统计模型参数数量
total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print("Total parameters: {}".format(total_params))

Total parameters: 3344256


In [17]:
import torch.nn.functional as F

class Conv1d(nn.Module): 
    def __init__(self, in_channels, out_channels, kernel_size, stride=(1,),
                 dilation=(1,), if_bias=False, relu=True, same_padding=True, bn=True):
        super(Conv1d, self).__init__()
        p0 = int((kernel_size[0] - 1) / 2) if same_padding else 0
        self.conv = nn.Conv1d(in_channels, out_channels, kernel_size=kernel_size, stride=stride, padding=p0,
                              dilation=dilation, bias=True if if_bias else False)
        self.bn = nn.BatchNorm1d(out_channels) if bn else None
        self.relu = nn.ReLU(inplace=True) if relu else None
        # self.relu = nn.SELU(inplace=True) if relu else None

    def forward(self, x):
        x = self.conv(x)
        if self.bn is not None:
            x = self.bn(x)
        if self.relu is not None:
            x = self.relu(x)
        x = F.dropout(x, 0.3, training=self.training)
        return x

In [18]:
class multiscale(nn.Module):
    def __init__(self, in_channel, out_channel):
        super(multiscale, self).__init__()

        self.conv0 = Conv1d(in_channel, out_channel, kernel_size=(1,), same_padding=False)

        self.conv1 = nn.Sequential(
            Conv1d(in_channel, out_channel, kernel_size=(1,), same_padding=False, bn=False),
            Conv1d(out_channel, out_channel, kernel_size=(3,), same_padding=True),
        )

        self.conv2 = nn.Sequential(
            Conv1d(in_channel, out_channel, kernel_size=(1,), same_padding=False),
            Conv1d(out_channel, out_channel, kernel_size=(5,), same_padding=True),
            Conv1d(out_channel, out_channel, kernel_size=(5,), same_padding=True),
        )

        self.conv3 = nn.Sequential(
            Conv1d(in_channel, out_channel, kernel_size=(1,), same_padding=False),
            Conv1d(out_channel, out_channel, kernel_size=(7,), same_padding=True),
            Conv1d(out_channel, out_channel, kernel_size=(7,), same_padding=True),
            Conv1d(out_channel, out_channel, kernel_size=(7,), same_padding=True)
        )

    def forward(self, x):

        x0 = self.conv0(x)
        x1 = self.conv1(x)
        x2 = self.conv2(x)
        x3 = self.conv3(x)

        x4 = torch.cat([x0, x1, x2, x3], dim=1) # batch_size * 4outchannel * len
        return x4 + x

In [19]:
from math import log

class Net(nn.Module):
    def __init__(self, k=3):
        super().__init__()
        base_channel = 8
        number_of_layers = int(log(101-k+1, 2))

        self.conv0 = CNNblock()
        
        self.multiscale = multiscale(128, 32)
        # self.dpcnn = DPCNN(64 * 4, number_of_layers)
        
    def forward(self, bert_embedding):
        x0 = bert_embedding  # (N, 768, 99)
        x0 = self.conv0(x0)
        x0 = self.multiscale(x0)

        return (x0)

In [20]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = Net().to(device)

In [21]:
total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print("Total parameters: {}".format(total_params))

Total parameters: 3396032


In [22]:
input = torch.randn(24, 6, 2048).to(device)  # [batch_size, max_len, embedding_dim]
input = input.permute(0, 2, 1)    # 交换维度：[batch_size, embedding_dim, max_len]
out = model(input)                # [batch_size, out_channels, n+2p-f/s+1]
print(out.shape)   

torch.Size([24, 128, 6])


In [23]:
.

SyntaxError: invalid syntax (1933637684.py, line 1)

In [88]:
import torch.nn.functional as F

class Conv1d(nn.Module): 
    def __init__(self, in_channels, out_channels, kernel_size, stride=(1,),
                 dilation=(1,), if_bias=False, relu=True, same_padding=True, bn=True):
        super(Conv1d, self).__init__()
        p0 = int((kernel_size[0] - 1) / 2) if same_padding else 0
        self.conv = nn.Conv1d(in_channels, out_channels, kernel_size=kernel_size, stride=stride, padding=p0,
                              dilation=dilation, bias=True if if_bias else False)
        self.bn = nn.BatchNorm1d(out_channels) if bn else None
        self.relu = nn.ReLU(inplace=True) if relu else None
        # self.relu = nn.SELU(inplace=True) if relu else None

    def forward(self, x):
        x = self.conv(x)
        if self.bn is not None:
            x = self.bn(x)
        if self.relu is not None:
            x = self.relu(x)
        x = F.dropout(x, 0.3, training=self.training)
        return x

In [89]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# 定义MLP模型
class CNNblock(nn.Module):
    def __init__(self):
        super(CNNblock, self).__init__()
        self.conv0 = nn.Sequential(nn.Conv1d(in_channels=1024, out_channels=256, kernel_size=3, stride=1, padding=1),
                                   nn.BatchNorm1d(num_features=256),
                                   nn.ReLU(),
                                   ) 
        
        self.conv1 = nn.Sequential(nn.Conv1d(in_channels=256, out_channels=64, kernel_size=3, stride=1, padding=1),
                                   nn.BatchNorm1d(num_features=64),
                                   nn.ReLU(),
                                   )

    def forward(self, x):
        x = self.conv0(x)
        x = F.dropout(x, 0.3, training=self.training)
        x = self.conv1(x)
        x = F.dropout(x, 0.3, training=self.training)
        # x = self.conv3(x)
        return x


In [90]:
class CNNblock1(nn.Module):
    def __init__(self) -> None:
        super(CNNblock1, self).__init__()
        self.conv0 = nn.Sequential(Conv1d(1024, 256, kernel_size=(1,), stride=1),
                                   Conv1d(256, 64, kernel_size=(1,), stride=1),
                                   )
        
    def forward(self, x):
        x = self.conv0(x)
        
        return x
        
            

In [91]:
class multiscale(nn.Module):
    def __init__(self, in_channel, out_channel):
        super(multiscale, self).__init__()

        self.conv0 = Conv1d(in_channel, out_channel, kernel_size=(1,), same_padding=False)

        self.conv1 = nn.Sequential(
            Conv1d(in_channel, out_channel, kernel_size=(1,), same_padding=False, bn=False),
            Conv1d(out_channel, out_channel, kernel_size=(3,), same_padding=True),
        )

        self.conv2 = nn.Sequential(
            Conv1d(in_channel, out_channel, kernel_size=(1,), same_padding=False),
            Conv1d(out_channel, out_channel, kernel_size=(5,), same_padding=True),
            Conv1d(out_channel, out_channel, kernel_size=(5,), same_padding=True),
        )

        self.conv3 = nn.Sequential(
            Conv1d(in_channel, out_channel, kernel_size=(1,), same_padding=False),
            Conv1d(out_channel, out_channel, kernel_size=(7,), same_padding=True),
            Conv1d(out_channel, out_channel, kernel_size=(7,), same_padding=True),
            Conv1d(out_channel, out_channel, kernel_size=(7,), same_padding=True)
        )

    def forward(self, x):

        x0 = self.conv0(x)
        x1 = self.conv1(x)
        x2 = self.conv2(x)
        x3 = self.conv3(x)

        x4 = torch.cat([x0, x1, x2, x3], dim=1) # batch_size * 4outchannel * len
        return x4 + x

In [92]:
from math import log

class Net(nn.Module):
    def __init__(self, k=3):
        super().__init__()
        base_channel = 8
        number_of_layers = int(log(101-k+1, 2))

        self.conv_s2v = CNNblock1()
        self.conv_lm = CNNblock1()
        
        self.multiscale_s2v = multiscale(64, 16)
        self.multiscale_lm = multiscale(64, 16)
        # self.dpcnn = DPCNN(64 * 4, number_of_layers)
        
    def forward(self, s2v_embedding, lm_embedding):
        x0 = s2v_embedding # (N, 768, 99)
        x1 = lm_embedding
        x0 = self.conv_s2v(x0)
        x1 = self.conv_lm(x1)
        x0 = self.multiscale_s2v(x0)
        x = torch.cat([x0, x1], dim=1)

        return (x)

In [93]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = Net().to(device)
total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print("Total parameters: {}".format(total_params))

Total parameters: 584512


In [94]:
s2v = torch.randn(24, 6, 1024).to(device)  # [batch_size, max_len, embedding_dim]
lm = torch.randn(24, 6, 1024).to(device)

s2v = s2v.permute(0, 2, 1)    # 交换维度：[batch_size, embedding_dim, max_len]
lm = lm.permute(0, 2, 1)

out = model(s2v, lm)                # [batch_size, out_channels, n+2p-f/s+1]
print(out.shape) 

torch.Size([24, 128, 6])


In [95]:
print(out[0].shape)
print(out[0, :, :4].shape)

torch.Size([128, 6])
torch.Size([128, 4])


In [96]:
a = out[0, :, :4]
print(a.shape)
print(a[:, 0].shape)

torch.Size([128, 4])
torch.Size([128])


In [97]:
.

SyntaxError: invalid syntax (1933637684.py, line 1)

In [ ]:
from featurization import load_seqs, seq2vec_encoding, lm_encoding

fasta_file = '/media/cnj/T9/data/test_data/positive/demo.fasta'

seq_ids, seqs, labels = load_seqs(fasta_file, 1, task='cls')

s2v_folder = s2v_folder = '/'.join(fasta_file.split('/')[:-1]) + '/s2v/'
lm_folder = s2v_folder = '/'.join(fasta_file.split('/')[:-1]) + '/lm/'

s2v = seq2vec_encoding(seq_ids, s2v_folder)
lm = lm_encoding(seq_ids, lm_folder)

arr = lm
s = arr[0]

running seq2vec encoding ...
running language model encoding ...


In [ ]:
import numpy as np

s = [np.mean(_) for _ in arr]
m = [np.max(_) for _ in arr]
n = [np.min(_) for _ in arr]
print(s)
print(m)
print(n)

[0.00087059196, 0.0012645025, -0.00033165189]
[1.2765226, 1.5807639, 1.7438128]
[-1.6460301, -1.5264282, -1.4460856]


In [ ]:

def array2d_norm(array_2d):
    
    mean = np.mean(array_2d, axis=0)
    std = np.std(array_2d, axis=0)

    std_array = np.divide(np.subtract(array_2d, mean), std)
    
    return std_array

t = arr[0]

nt = array2d_norm(t)
print(np.mean(nt, axis=0))


[-1.7092509e-08  2.0598664e-08 -3.8567713e-08 ... -1.2723510e-08
  2.8049245e-08  3.1555402e-08]


In [ ]:
x = torch.randn(8, 6)
pad_x = torch.nn.functional.pad(x, (0, 4))
pad_x.shape

torch.Size([8, 10])

In [6]:
x = torch.randn(8, 6)


torch.Size([6, 8])

In [ ]:
.

In [ ]:
x = torch.randn(3, 100, 2048)
x.shape

torch.Size([3, 100, 2048])

In [ ]:
a = model(x.permute(0,2,1))
print(a.shape)
print(a.permute(0,2,1).shape)

TypeError: forward() missing 1 required positional argument: 'structure'

In [3]:
import torch
from torch_geometric.data import Data
from torch_geometric.loader import DataLoader

class MyData(Data):
    def __cat_dim__(self, key, value, *args, **kwargs):
        if key == 'foo':
            return None
        return super().__cat_dim__(key, value, *args, **kwargs)

class MyData(Data): 
    def __inc__(self, key, value, *args, **kwargs):
        if 'index' in key:
            return self.num_nodes
        else:
            return 0

    def __cat_dim__(self, key, value, *args, **kwargs):
        if 'index' in key:
            return 1
        else:
            return 0    


edge_index = torch.tensor([
   [0, 1, 1, 2],
   [1, 0, 2, 1],
])
foo = torch.randn(16)

data = MyData(num_nodes=3, edge_index=edge_index, foo=foo)

print(data)

data_list = [data, data]
loader = DataLoader(data_list, batch_size=2)
batch = next(iter(loader))

print(batch)


MyData(edge_index=[2, 4], num_nodes=3, foo=[16])
MyDataBatch(edge_index=[2, 8], num_nodes=6, foo=[2, 16], batch=[6], ptr=[3])


In [9]:
from torch_geometric.datasets import Planetoid

dataset = Planetoid(root='/tmp/Cora', name='Cora')

Processing...
Done!


In [12]:
import torch
import torch.nn.functional as F
from torch_geometric.nn import GCNConv

class GCN(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = GCNConv(dataset.num_node_features, 16)
        self.conv2 = GCNConv(16, dataset.num_classes)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index

        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, training=self.training)
        x = self.conv2(x, edge_index)

        return F.log_softmax(x, dim=1)

In [17]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = GCN().to(device)
print(model)
data = dataset[0].to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)

model.train()
for epoch in range(200):
    optimizer.zero_grad()
    out = model(data)
    loss = F.nll_loss(out[data.train_mask], data.y[data.train_mask])
    loss.backward()
    optimizer.step()

GCN(
  (conv1): GCNConv(1433, 16)
  (conv2): GCNConv(16, 7)
)


In [14]:
model.eval()
pred = model(data).argmax(dim=1)
correct = (pred[data.test_mask] == data.y[data.test_mask]).sum()
acc = int(correct) / int(data.test_mask.sum())
print(f'Accuracy: {acc:.4f}')
# >>> Accuracy: 0.8150

Accuracy: 0.7980


In [7]:
import csv

best_epoch = 10
best_acc = 0.85
best_auc = 0.92

data = {
    'bestepoch': str(best_epoch),
    'acc': str(best_acc),
    'auc': str(best_auc)
}

filename = 'model_stats.csv'
file_exists = False
try:
    with open(filename, 'r') as csvfile:
        reader = csv.reader(csvfile)
        headers = next(reader)
        if headers == ['bestepoch', 'acc', 'auc']:
            file_exists = True
except FileNotFoundError:
    pass

with open(filename, 'a', newline='') as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=['bestepoch', 'acc', 'auc'])
    if not file_exists:
        writer.writeheader()
    writer.writerow(data)

In [9]:
exp_id ='train_with_cnn_k3_1'
exp_id.split('_')[-1]

'1'

In [12]:
a = ['t', 1, 2, 3]
print(a[0])
print(a[1:])
# for i in range(3):
b = a[1:]
c = [i + 5 for i in a[1:]]
print(c)

list = []
list.append(b)
print(list)
list.append(c)
print(list)

ave_list = m

t
[1, 2, 3]
[6, 7, 8]
[[1, 2, 3]]
[[1, 2, 3], [6, 7, 8]]


In [17]:
aves = [sum(column) / len(column) for column in zip(*list)]
aves

[3.5, 4.5, 5.5]

In [20]:
import numpy as np

np.array(list)

array([[1, 2, 3],
       [6, 7, 8]])

In [9]:
import os
import datetime


def current_time():
    return datetime.datetime.now().strftime("%Y-%m-%d_%H.%M.%S")

a = 'saved_models/acc_cnnk5.model_0'

acc = 0.9

b = a.replace('.', f'.acc{acc}.')

b

'saved_models/acc_cnnk5.acc0.9.model_0'

In [2]:
import numpy as np

# 假设有两个一一对应的数组
array1 = np.array(['A', 'B', 'C', 'D', 'E'])
array2 = np.array([1, 2, 3, 4, 5])

# 设置随机种子
random_seed = 42
np.random.seed(random_seed)

# 创建随机索引数组
random_indices = np.random.permutation(len(array1))

# 使用随机索引数组对两个数组进行索引
shuffled_array1 = array1[random_indices]
shuffled_array2 = array2[random_indices]

# 打印结果
print("Shuffled array1:", shuffled_array1)
print("Shuffled array2:", shuffled_array2)

Shuffled array1: ['B' 'E' 'C' 'A' 'D']
Shuffled array2: [2 5 3 1 4]


In [9]:
k_fold = False

if not k_fold:
    print('1')

1


In [15]:
import re

def load_cv_seqs(fasta_file, task):
    seq_ids = []
    seqs = []
    labels = []
    pattern = re.compile('[^ARNDCQEGHILKMFPSTWYV]')
    
    with open(fasta_file, 'r') as f:
        lines = f.readlines()
        for line in lines:
            line = line.strip()
            
            if line[0] == '>':
                id = line.split('|')[0]
                label = line.split('|')[1]
                seq_ids.append(id)
                labels.append(label)
                
            elif len(pattern.findall(line)) == 0:
                seqs.append(line)
                
    labels = np.array([float(x) for x in labels])
    
    return seq_ids, seqs, labels
                
load_cv_seqs('/home/cnj/cs/test_methods/cross_val/10_fold_cnnk3_gat_2023-12-11_17.46.53/data/1_fold/test.fasta', 'cls')

(['>LAMP_L08AP00018', '>LAMP_L06AT00005'],
 ['KWKSFIKKLTSKALHSAKKF', 'RVCESQSHGFKGACTGDHNCALVCRNEGFSGGNCRGFRRRCFCTLKC'],
 array([1., 1.]))

In [3]:
import torch
import torch.nn as nn

class MLP(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(MLP, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, num_classes)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.fc1(x)
        x = torch.relu(x)
        x = self.fc2(x)
        x = self.sigmoid(x)
        return x

input_size = 10  # 输入特征的维度
hidden_size = 20  # 隐层的大小
num_classes = 5  # 标签的数量

model = MLP(input_size, hidden_size, num_classes)

# 假设有样本 x，维度为 (batch_size, input_size)
x = torch.randn(4, input_size)

# 模型预测
pred = model(x)


In [4]:
pred.shape

torch.Size([4, 5])

In [5]:
pred

tensor([[0.5236, 0.3663, 0.4891, 0.5220, 0.4483],
        [0.5523, 0.3516, 0.3741, 0.3994, 0.4935],
        [0.4650, 0.4224, 0.4386, 0.3916, 0.4833],
        [0.5146, 0.4080, 0.3521, 0.3790, 0.4040]], grad_fn=<SigmoidBackward0>)

In [8]:
bacteria = ['E. coli', 'S. aureus', 'P. aeruginosa']
bac = ['E. coli', 'S. aureus']

output = [1 if b in bac else 0 for b in bacteria]

print(output)


[1, 1, 0]


In [11]:
from skmultilearn.dataset import load_dataset
from collections import Counter
import pandas as pd

In [4]:
X,y, _, _ = load_dataset('scene', 'undivided')


scene:undivided - does not exists downloading
Downloaded scene-undivided


In [12]:
from skmultilearn.model_selection.measures import get_combination_wise_output_matrix
Counter(combination for row in get_combination_wise_output_matrix(y.A, order=2) for combination in row)

Counter({(4, 4): 533,
         (0, 4): 38,
         (0, 0): 427,
         (5, 5): 431,
         (0, 5): 19,
         (1, 1): 364,
         (2, 2): 397,
         (2, 3): 24,
         (3, 3): 433,
         (2, 4): 14,
         (3, 4): 76,
         (4, 5): 1,
         (3, 5): 6,
         (0, 3): 1})

In [13]:
_, original_y_train, _, _ = load_dataset('scene', 'train')
_, original_y_test, _, _ = load_dataset('scene', 'test')

original_y_train.data

scene:train - exists, not redownloading
scene:test - exists, not redownloading


array([list([1, 1]), list([1, 1]), list([1]), ..., list([1]), list([1]),
       list([1])], dtype=object)

In [14]:
pd.DataFrame({
    'train': Counter(str(combination) for row in get_combination_wise_output_matrix(original_y_train.A, order=2) for combination in row),
    'test' : Counter(str(combination) for row in get_combination_wise_output_matrix(original_y_test.A, order=2) for combination in row)
}).T.fillna(0.0)

(4, 4)  (0, 4)  (0, 0)  (5, 5)  (0, 5)  (1, 1)  (2, 2)  (2, 3)  (3, 3)  \
train   277.0    21.0   227.0   224.0    12.0   165.0   197.0     8.0   196.0   
test    256.0    17.0   200.0   207.0     7.0   199.0   200.0    16.0   237.0   

       (2, 4)  (3, 4)  (4, 5)  (3, 5)  (0, 3)  
train     6.0    27.0     1.0     1.0     0.0  
test      8.0    49.0     0.0     5.0     1.0

In [ ]:
.

In [15]:

from skmultilearn.model_selection import iterative_train_test_split
X_train, y_train, X_test, y_test = iterative_train_test_split(X, y, test_size = 0.5)

In [16]:
pd.DataFrame({
    'train': Counter(str(combination) for row in get_combination_wise_output_matrix(y_train.A, order=2) for combination in row),
    'test' : Counter(str(combination) for row in get_combination_wise_output_matrix(y_test.A, order=2) for combination in row)
}).T.fillna(0.0)

(5, 5)  (0, 5)  (0, 0)  (4, 4)  (0, 4)  (1, 1)  (2, 2)  (2, 3)  (3, 3)  \
train   215.0    10.0   214.0   267.0    19.0   182.0   198.0    12.0   217.0   
test    216.0     9.0   213.0   266.0    19.0   182.0   199.0    12.0   216.0   

       (2, 4)  (3, 4)  (4, 5)  (3, 5)  (0, 3)  
train     7.0    38.0     1.0     3.0     1.0  
test      7.0    38.0     0.0     3.0     0.0

In [ ]:
.

In [ ]:
import numpy as np
from sklearn.model_selection import StratifiedShuffleSplit

In [4]:
import os

input_fasta = '/home/cnj/cs/test_methods/data/mul_label_data/multilabel_demo.fasta'
sa3m_folder = '/home/cnj/cs/test_methods/data/mul_label_data/single_a3m/'

ids = []
seqs = []
with open(input_fasta, 'r') as f:
    lines = f.readlines()
    print(f'Num of fasta seqs is {len(lines)/2}')
    for line in lines:
            line = line.strip()
            if line[0] == '>':
                ids.append(line)
            else:
                seqs.append(line)
                
    if not os.path.exists(sa3m_folder):
        os.makedirs(sa3m_folder)
        
    for f in os.listdir(sa3m_folder):
        os.remove(sa3m_folder + f)
        
    for i in range(len(ids)):
        name = ids[i]
        fname = name.replace('|', '_')[1:]
        seq = seqs[i]
        with open(sa3m_folder + fname + '.a3m', 'w') as f:
            f.write(name + '\n')
            f.write(seq)

Num of fasta seqs is 5.0


In [5]:



def count(f):
    line_count = 0
    with open(f, 'r') as file:
        for line in file:
            line_count += 1

    print("Total number of lines:", line_count)
    
count('/home/cnj/cs/test_methods/data/mll_func/multiAMP_test.csv')
count('/home/cnj/cs/test_methods/data/mll_func/multiAMP_train.csv')
count('/home/cnj/cs/test_methods/data/mll_func/PAAC.tsv')

Total number of lines: 686
Total number of lines: 6161
Total number of lines: 10479


In [4]:
import pandas as pd

df = pd.read_csv('/home/cnj/cs/test_methods/data/mll_func/test.csv', encoding='utf8')
df

id                                           sequence  \
0    dbAMP_18382                                        KKLGLCLGLKK   
1    dbAMP_21204                                     KLPKLLKKLLKLLK   
2    dbAMP_18425           GFGCNGPWDEDDMKCHNHCKTIKGYKGGYCASAGFVCKCY   
3    dbAMP_05713  LEYKGECFTKDNTCKYKIDGKTYLAKCPSAANTKCEKDGNKCTYDS...   
4    dbAMP_15569                                  FVKLKKIANIINSIFKK   
..           ...                                                ...   
680  dbAMP_16207                                      FKRIHQRIKDFLR   
681  dbAMP_04747                                      ILPFLAGLFSKIL   
682  dbAMP_16054                                       KRIRKRIKKWKR   
683  dbAMP_17719                               VDKGRYLEAPTPPRPIYNRN   
684  dbAMP_14795                                    KWKLFKKIPHLAKKF   

     Antibacterial  MammalianCells  Antifungal  Antiviral  Anticancer  \
0                1               1           0          0           1   
1                1               1           0          0           0   
2                1               0           0          0           0   
3                0               0           1          0           0   
4                0               1           1          0           1   
..             ...             ...         ...        ...         ...   
680              1               1           0          0           0   
681              1               0           1          1           0   
682              1               1           0          0           0   
683              1               0           0          0           0   
684              1               1           0          0           1   

     Antiparasitic  
0                0  
1                0  
2                0  
3                0  
4                0  
..             ...  
680              0  
681              0  
682              0  
683              0  
684              0  

[685 rows x 8 columns]

In [5]:
# df = df.drop(df.columns[2], axis=1)
df = df.drop(df.columns[7:], axis=1)
df


id                                           sequence  \
0    dbAMP_18382                                        KKLGLCLGLKK   
1    dbAMP_21204                                     KLPKLLKKLLKLLK   
2    dbAMP_18425           GFGCNGPWDEDDMKCHNHCKTIKGYKGGYCASAGFVCKCY   
3    dbAMP_05713  LEYKGECFTKDNTCKYKIDGKTYLAKCPSAANTKCEKDGNKCTYDS...   
4    dbAMP_15569                                  FVKLKKIANIINSIFKK   
..           ...                                                ...   
680  dbAMP_16207                                      FKRIHQRIKDFLR   
681  dbAMP_04747                                      ILPFLAGLFSKIL   
682  dbAMP_16054                                       KRIRKRIKKWKR   
683  dbAMP_17719                               VDKGRYLEAPTPPRPIYNRN   
684  dbAMP_14795                                    KWKLFKKIPHLAKKF   

     Antibacterial  MammalianCells  Antifungal  Antiviral  Anticancer  
0                1               1           0          0           1  
1                1               1           0          0           0  
2                1               0           0          0           0  
3                0               0           1          0           0  
4                0               1           1          0           1  
..             ...             ...         ...        ...         ...  
680              1               1           0          0           0  
681              1               0           1          1           0  
682              1               1           0          0           0  
683              1               0           0          0           0  
684              1               1           0          0           1  

[685 rows x 7 columns]

In [6]:
df.to_csv('/home/cnj/cs/test_methods/data/mll_func/test.csv', index=False)

In [15]:
df = pd.read_csv('/home/cnj/cs/test_methods/data/mll_func/multiAMP_train.csv')
df[df['sequence'].str.len() > 100]
# df[(df['Antibacterial'] == 1)]
#    & (df['is_validated'] == 'YES')]


ID                                           sequence  \
3     dbAMP_00006  AAEFPDFYDSEEQMGPHQEAEDEKDRADQRVLTEEEKKELENLAAM...   
4     dbAMP_00027                        AAGGVKKPKKAAAAKKSPKKPKKPAAA   
5     dbAMP_00029  AAGNPSETGGAVATYSTAVGSFLDGTVKVVATGGASRVPGNCGTAA...   
7     dbAMP_00036                                  AAIYPFGIKIRCKAAFC   
8     dbAMP_00037                                  AAKIILNPKFRCKAAFC   
...           ...                                                ...   
6155  dbAMP_28611                       VKRALSALKPKNKRFIGGIISFIKKLFG   
6156  dbAMP_28617                                    VNRKKILGKSIKVVK   
6157  dbAMP_28628                                      VRRFPAAAPFLRR   
6158  dbAMP_28659                                 YGAAKKAAKAAKKAAKAA   
6159  dbAMP_28660                                 YGAKAKAAKAAKAKAAKA   

     is_validated  Antibacterial  MammalianCells  Antifungal  Antiviral  \
3             YES              1               0           0          0   
4             YES              1               0           0          0   
5              NO              1               0           0          0   
7              NO              1               0           1          0   
8             YES              1               1           1          0   
...           ...            ...             ...         ...        ...   
6155          YES              1               0           0          0   
6156          YES              1               0           0          0   
6157          YES              1               1           1          0   
6158          YES              1               1           0          0   
6159          YES              1               1           0          0   

      Anticancer  Antiparasitic         A  ...  solventaccess_C2_001  \
3              0              0  0.116667  ...              5.000000   
4              0              0  0.333333  ...             22.222222   
5              0              0  0.160920  ...              4.597701   
7              0              0  0.235294  ...             52.941176   
8              1              0  0.235294  ...             17.647059   
...          ...            ...       ...  ...                   ...   
6155           0              0  0.071429  ...              7.142857   
6156           0              0  0.000000  ...             13.333333   
6157           0              0  0.230769  ...             15.384615   
6158           0              0  0.555556  ...             27.777778   
6159           0              0  0.555556  ...             22.222222   

      solventaccess_C2_025  solventaccess_C2_050  solventaccess_C2_075  \
3                31.666667             48.333333             68.333333   
4                25.925926             55.555556             70.370370   
5                32.183908             59.770115             78.160920   
7                52.941176             52.941176             64.705882   
8                17.647059             41.176471             52.941176   
...                    ...                   ...                   ...   
6155             10.714286             39.285714             46.428571   
6156             13.333333             26.666667             60.000000   
6157             15.384615             23.076923             92.307692   
6158             27.777778             50.000000             66.666667   
6159             22.222222             50.000000             66.666667   

      solventaccess_C2_100  solventaccess_C3_001  solventaccess_C3_025  \
3               100.000000              8.333333             13.333333   
4                85.185185             29.629630             29.629630   
5               100.000000              5.747126             17.241379   
7                76.470588             23.529412             23.529412   
8                76.470588             47.058824             47.058824   
...                    ...                   ...   

In [ ]:
.

In [20]:
from Bio import SeqIO
import numpy as np

def get_fasta_sequence_lengths(filename):
    lengths = []
    max_length = 0

    for record in SeqIO.parse(filename, "fasta"):
        sequence_length = len(record.seq)
        lengths.append(sequence_length)
        if sequence_length > max_length:
            max_length = sequence_length

    return lengths, max_length

# 读取 FASTA 文件并获取序列长度
filename = "/home/cnj/cs/test_methods/data/cv_data/acp_test/acp_test_all.fasta"
sequence_lengths, max_sequence_length = get_fasta_sequence_lengths(filename)

sequence_lengths = np.array(sequence_lengths)
# 打印所有序列的长度和最长序列的长度
# print("Sequence Lengths:", sequence_lengths)
print("Max Sequence Length:", max_sequence_length)
print(np.unique(sequence_lengths))

Max Sequence Length: 207
[  5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22
  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40
  41  42  43  44  45  46  47  48  49  50  51  52  53  54  75  81  83  84
  85  86  90 108 111 207]


In [16]:
sequence_lengths[sequence_lengths>100]

array([101, 114, 107, 121])

In [27]:
np.count_nonzero(sequence_lengths == 255)

1

In [ ]:
# 处理大于100的序列

In [1]:
# 输入文件路径和名称
input_file = '/home/cnj/cs/test_methods/data/cv_data/acp_train/acp_train_all.fasta'
# 输出文件路径和名称
output_file = '/home/cnj/cs/test_methods/data/cv_data/acp_train/acp_train_all_145.fasta'

# 读取输入文件并处理序列
sequences = []
with open(input_file, 'r') as input_handle:
    header = ''
    sequence = ''
    for line in input_handle:
        line = line.strip()
        if line.startswith('>'):  # 处理标题行
            if sequence and len(sequence) <= 100:  # 仅保留长度小于等于 100 的序列
                sequences.append((header, sequence))
            header = line
            sequence = ''
        else:  # 处理序列行
            sequence += line

    # 处理最后一个序列
    if sequence and len(sequence) <= 100:
        sequences.append((header, sequence))

# 将筛选后的序列保存到输出文件
with open(output_file, 'w') as output_handle:
    for header, sequence in sequences:
        output_handle.write(f'{header}\n{sequence}\n')

In [3]:
len(sequences)

12847